import { dbId, getPage, notion, queryAll } from "@/lib/notion";
import { relationIds, selectProp, textProp } from "@/lib/notion/properties";
import { mapShift, type Shift } from "@/lib/domain/shift";
import type { Staff } from "@/lib/domain/staff";
import { SCHEDULE_DAYS } from "@/lib/domain/staff-schedule";
import type { NotionPage } from "@/lib/notion/types";

const TZ = "Asia/Ho_Chi_Minh";
const WEEK_SOURCE = process.env.NOTION_WEEK_DB_ID || "3218156e-326f-80ba-ac6a-000be0178f23";
const DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] as const;

type Week = { id: string; name: string; start: string; end: string };
export type ShiftRegistration = { id: string; weekId: string; weekName: string; weekStart: string; weekEnd: string; status: string; editable: boolean; availableShifts: Shift[]; shifts: Record<string, Shift[]> };
function record(value: unknown): Record<string, unknown> | null { return value && typeof value === "object" ? (value as Record<string, unknown>) : null; }
function formulaDate(page: NotionPage, name: string): string { const property = record(page.properties[name]); const formula = record(property?.formula); const date = record(formula?.date); if (typeof date?.start === "string") return date.start.slice(0, 10); const string = formula?.string; if (typeof string === "string") { const iso = string.match(/\d{4}-\d{2}-\d{2}/)?.[0]; if (iso) return iso; const dmY = string.match(/(\d{2})[/-](\d{2})[/-](\d{4})/); if (dmY) return `${dmY[3]}-${dmY[2]}-${dmY[1]}`; } return ""; }
function addDays(value: string, amount: number): string { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + amount); return date.toISOString().slice(0, 10); }
function localDateParts(): { date: string; weekday: number } { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: TZ, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short" }).formatToParts(new Date()); const get = (type: string) => parts.find((part) => part.type === type)?.value ?? ""; const date = `${get("year")}-${get("month")}-${get("day")}`; return { date, weekday: ({ Mon: 1, Tue: 2, Wed: 3, Thu: 4, Fri: 5, Sat: 6, Sun: 0 } as Record<string, number>)[get("weekday")] ?? 0 }; }
export function registrationWindow(): { open: boolean; targetMonday: string } { const { date, weekday } = localDateParts(); const daysUntilMonday = weekday === 6 ? 2 : weekday === 0 ? 1 : 8 - weekday; return { open: weekday === 6 || weekday === 0, targetMonday: addDays(date, daysUntilMonday) }; }
async function findNextWeek(targetMonday: string): Promise<Week | null> { const pages = await queryAll(WEEK_SOURCE); const candidates = await Promise.all(pages.map(async (page) => { try { const full = await getPage(page.id); const start = formulaDate(full, "Monday Start on"); if (start !== targetMonday) return null; return { id: full.id, name: textProp(full, "Name"), start, end: formulaDate(full, "Saturday Date") || addDays(start, 6) }; } catch { return null; } })); return candidates.find((candidate): candidate is Week => Boolean(candidate)) ?? null; }
async function activeShifts(): Promise<Shift[]> { return (await queryAll(dbId("NOTION_SHIFT_MASTER_DB_ID"))).map(mapShift).filter((shift) => shift.active); }
function registrationFromPage(page: NotionPage, week: Week, shifts: Shift[], editable: boolean): ShiftRegistration { const byId = new Map(shifts.map((shift) => [shift.id, shift])); const shiftMap = Object.fromEntries(DAY_NAMES.map((day) => [day, relationIds(page, `${day} Shifts`).map((id) => byId.get(id)).filter((shift): shift is Shift => Boolean(shift))])); return { id: page.id, weekId: week.id, weekName: week.name, weekStart: week.start, weekEnd: week.end, status: selectProp(page, "Schedule Status") || "Draft", editable, availableShifts: shifts, shifts: shiftMap }; }
async function existingRegistration(staff: Staff, week: Week): Promise<NotionPage | null> { const pages = await queryAll(dbId("NOTION_SCHEDULE_DB_ID")); return pages.find((page) => relationIds(page, "Staff")[0] === staff.id && relationIds(page, "Week")[0] === week.id) ?? null; }
export async function getShiftRegistration(staff: Staff): Promise<ShiftRegistration | null> { const window = registrationWindow(); if (!window.open) return null; const week = await findNextWeek(window.targetMonday); if (!week) return null; const shifts = await activeShifts(); const page = await existingRegistration(staff, week); if (!page) return { id: "", weekId: week.id, weekName: week.name, weekStart: week.start, weekEnd: week.end, status: "Draft", editable: true, availableShifts: shifts, shifts: Object.fromEntries(DAY_NAMES.map((day) => [day, []])) }; return registrationFromPage(page, week, shifts, ["Draft", "Submitted"].includes(selectProp(page, "Schedule Status"))); }
function relationProperty(ids: string[]) { return { relation: ids.map((id) => ({ id })) }; }
async function resolveTargetWeek(weekId: string): Promise<Week> { const window = registrationWindow(); if (!window.open) throw new Error("REGISTRATION_CLOSED"); const pages = await queryAll(WEEK_SOURCE); if (!pages.some((page) => page.id === weekId)) throw new Error("INVALID_WEEK"); const full = await getPage(weekId); const start = formulaDate(full, "Monday Start on"); if (start !== window.targetMonday) throw new Error("INVALID_WEEK"); return { id: full.id, name: textProp(full, "Name"), start, end: formulaDate(full, "Saturday Date") || addDays(start, 6) }; }
export async function saveShiftRegistration(staff: Staff, weekId: string, selected: Record<string, string[]>): Promise<ShiftRegistration> { const week = await resolveTargetWeek(weekId); const shifts = await activeShifts(); const validIds = new Set(shifts.map((shift) => shift.id)); const existing = await existingRegistration(staff, week); const currentStatus = existing ? selectProp(existing, "Schedule Status") : "Draft"; if (existing && !["Draft", "Submitted"].includes(currentStatus)) throw new Error("REGISTRATION_LOCKED"); const props: Record<string, unknown> = { "Schedule Status": { select: { name: currentStatus === "Submitted" ? "Submitted" : "Draft" } } }; for (const [day] of SCHEDULE_DAYS) props[`${day} Shifts`] = relationProperty((selected[day] ?? []).filter((id) => validIds.has(id))); let pageId: string; if (existing) { await notion().pages.update({ page_id: existing.id, properties: props as never }); pageId = existing.id; } else { const created = await notion().pages.create({ parent: { data_source_id: dbId("NOTION_SCHEDULE_DB_ID") }, properties: { Name: { title: [{ text: { content: `${staff.name} · ${week.name}` } }] }, Staff: { relation: [{ id: staff.id }] }, Week: { relation: [{ id: week.id }] }, "Schedule Status": { select: { name: "Draft" } }, ...Object.fromEntries(SCHEDULE_DAYS.map(([day]) => [`${day} Shifts`, { relation: [] }])) } as never }); pageId = created.id; await notion().pages.update({ page_id: pageId, properties: props as never }); } return registrationFromPage(await getPage(pageId), week, shifts, true); }
export async function submitShiftRegistration(staff: Staff, weekId: string): Promise<ShiftRegistration> { const week = await resolveTargetWeek(weekId); const existing = await existingRegistration(staff, week); if (!existing) throw new Error("NO_REGISTRATION"); const status = selectProp(existing, "Schedule Status"); if (!["Draft", "Submitted"].includes(status)) throw new Error("REGISTRATION_LOCKED"); await notion().pages.update({ page_id: existing.id, properties: { "Schedule Status": { select: { name: "Submitted" } } } as never }); return registrationFromPage(await getPage(existing.id), week, await activeShifts(), true); }
