import{getCloudflareContext}from"@opennextjs/cloudflare";
import{authenticateWorkforce,WorkforceAuthError}from"@/lib/workforce-auth";
import{stagingWorkforceIdentity,type TosStagingAuthEnv}from"@/lib/tos-staging-auth";
import{callWorkforceCore,callWorkforceCoreWithStaffPin,type WorkforceCoreBinding}from"@/lib/workforce-core";
export const runtime="nodejs";export const dynamic="force-dynamic";
type Context={params:Promise<{path:string[]}>};type WorkforceEnv=TosStagingAuthEnv&{PINO_WORKFORCE_CORE:WorkforceCoreBinding;CF_ACCESS_TEAM_DOMAIN:string;CF_ACCESS_TOS_AUD:string};
async function handle(request:Request,context:Context){try{const{env}=await getCloudflareContext({async:true}) as unknown as{env:WorkforceEnv};const stagingIdentity=stagingWorkforceIdentity(request,env);const identity=stagingIdentity??await authenticateWorkforce(request.headers,{teamDomain:env.CF_ACCESS_TEAM_DOMAIN,audience:env.CF_ACCESS_TOS_AUD});const{path}=await context.params;let body:Record<string,unknown>={};const url=new URL(request.url);for(const[key,value]of url.searchParams)if(key!=="t"&&key!=="mobile"&&key!=="username")body[key]=value;if(request.method!=="GET"&&request.method!=="HEAD"){const parsed=await request.json().catch(()=>({}));if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed))body={...body,...parsed};}const idempotencyKey=request.headers.get("idempotency-key")?.trim()||undefined;const coreRequest={method:request.method,path:`/${path.join("/")}`,body,...(idempotencyKey?{idempotencyKey}: {})},token=cookie(request,"pino_staff_session");const result=token?await callWorkforceCoreWithStaffPin(env.PINO_WORKFORCE_CORE,coreRequest,token):await callWorkforceCore(env.PINO_WORKFORCE_CORE,coreRequest,identity);return Response.json(result.body,{status:result.status,headers:{"cache-control":"no-store","x-request-id":result.requestId}});}catch(error){if(error instanceof WorkforceAuthError)return Response.json({error:{code:"IDENTITY_AUTHENTICATION_FAILED",message:error.message}},{status:error.status,headers:{"cache-control":"no-store"}});console.error("Workforce facade failure",error instanceof Error?error.message:"unknown");return Response.json({error:{code:"PLATFORM_INTERNAL_ERROR",message:"An unexpected error occurred"}},{status:500});}}
function cookie(request:Request,name:string){return request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith(`${name}=`))?.slice(name.length+1)??"";}
export const GET=handle;export const POST=handle;export const PUT=handle;export const PATCH=handle;
