"use client";

import { useEffect, useMemo, useState } from "react";
import { LayeredCharacter, pinoriaAssetUrl, type PinoriaCharacterConfig, type PinoriaWardRender } from "@/app/pinoria-tv/layered-character";
import styles from "./pinoria-world.module.css";

type Status="DRAFT"|"ACTIVE"|"ARCHIVED"; type WorldType="CORE"|"SUMMER"|"SPECIAL"|"OTHER"; type InstanceStatus="LIVE"|"INACTIVE"|"REVOKED";
type Layer={id:string;sceneId:string;key:string;displayName:string;kind:"MEDIA"|"CHARACTER";mediaType:"PNG"|"WEBM"|null;assetKey:string|null;posterAssetKey:string|null;positionX:number;positionY:number;scale:number;zIndex:number;anchor:"CENTER"|"BOTTOM_CENTER";enabled:boolean;metadata:Record<string,unknown>;version:number};
type Scene={id:string;worldId:string;key:string;displayName:string;descriptionText:string;sortOrder:number;status:"ACTIVE"|"DISABLED";canvasWidth:number;canvasHeight:number;baseAssetKey:string;metadata:Record<string,unknown>;version:number;layers:Layer[]};
type World={id:string;key:string;displayName:string;descriptionText:string;worldType:WorldType;thumbnailAssetKey:string|null;metadata:Record<string,unknown>;status:Status;version:number;scenes:Scene[]};
type Learner={id:string;displayName:string;status:string;instanceCount:number;liveInstanceId:string|null};
type Character={id:string;config:PinoriaCharacterConfig;wardRender:PinoriaWardRender|null}|null;
type Instance={id:string;studentProfileId:string;worldId:string;displayLabel:string;status:InstanceStatus;grantedAt:string;revokedAt:string|null;version:number;world:World;sceneAccess:Record<string,boolean>;unlockedLayerIds:string[];character?:Character};
type Envelope<T>={data?:T;error?:{message?:string}};

async function api<T>(path:string,init?:RequestInit){const response=await fetch(`/api/bo/${path}`,{cache:"no-store",...init});const body=await response.json() as Envelope<T>;if(!response.ok||body.data===undefined)throw new Error(body.error?.message??"Pinoria World operation failed");return body.data;}
async function mutate<T>(path:string,method:"POST"|"PATCH"|"PUT"|"DELETE",body:unknown){return api<T>(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});}
async function upload(file:File){const form=new FormData();form.set("file",file);const response=await fetch("/api/bo/pinoria/worlds/media",{method:"POST",headers:{"idempotency-key":crypto.randomUUID()},body:form});const result=await response.json() as Envelope<{objectKey:string;mediaType:"PNG"|"WEBM"}>;if(!response.ok||!result.data)throw new Error(result.error?.message??"World media upload failed");return result.data;}
const n=(value:string)=>Number(value||0);

export function PinoriaWorldManager(){
 const[catalog,setCatalog]=useState<World[]>([]),[learners,setLearners]=useState<Learner[]>([]),[instances,setInstances]=useState<Instance[]>([]);
 const[worldId,setWorldId]=useState<string|null>(null),[sceneId,setSceneId]=useState<string|null>(null),[layerId,setLayerId]=useState<string|null>(null),[studentId,setStudentId]=useState<string|null>(null),[instanceId,setInstanceId]=useState<string|null>(null),[instanceSceneId,setInstanceSceneId]=useState<string|null>(null);
 const[mode,setMode]=useState<"WORLD"|"INSTANCE">("WORLD"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const world=catalog.find(x=>x.id===worldId)??catalog[0]??null,scene=world?.scenes.find(x=>x.id===sceneId)??world?.scenes[0]??null,layer=scene?.layers.find(x=>x.id===layerId)??scene?.layers[0]??null;
 const learner=learners.find(x=>x.id===studentId)??learners[0]??null,instance=instances.find(x=>x.id===instanceId)??instances[0]??null,instanceScene=instance?.world.scenes.find(x=>x.id===instanceSceneId)??instance?.world.scenes[0]??null;
 const totals=useMemo(()=>({scenes:catalog.reduce((a,w)=>a+w.scenes.length,0),layers:catalog.reduce((a,w)=>a+w.scenes.reduce((b,s)=>b+s.layers.length,0),0)}),[catalog]);
 async function loadCatalog(){const result=await api<{worlds:World[]}>("pinoria/worlds");setCatalog(result.worlds);if(!worldId&&result.worlds[0]){setWorldId(result.worlds[0].id);setSceneId(result.worlds[0].scenes[0]?.id??null);setLayerId(result.worlds[0].scenes[0]?.layers[0]?.id??null);}}
 async function loadLearners(){const result=await api<{learners:Learner[]}>("pinoria/worlds/learners");setLearners(result.learners);if(!studentId&&result.learners[0])setStudentId(result.learners[0].id);}
 async function loadInstances(id:string){const result=await api<{instances:Instance[]}>(`pinoria/worlds/learners/${id}`);const next=result.instances.find(x=>x.id===instanceId)??result.instances[0];let rows=result.instances;if(next){const detail=await api<Instance>(`pinoria/worlds/instances/${next.id}`);rows=result.instances.map(item=>item.id===detail.id?detail:item);}setInstances(rows);setInstanceId(next?.id??null);setInstanceSceneId(next?.world.scenes[0]?.id??null);}
 async function refresh(){await Promise.all([loadCatalog(),loadLearners()]);if(studentId)await loadInstances(studentId);}
 useEffect(()=>{void (async()=>{try{await Promise.all([loadCatalog(),loadLearners()]);}catch(e){setError(e instanceof Error?e.message:"Load failed");}})();},[]);
 useEffect(()=>{if(studentId)void loadInstances(studentId).catch(e=>setError(e instanceof Error?e.message:"Load failed"));},[studentId]);
 async function run(action:()=>Promise<void>,ok:string){setBusy(true);setError("");setMessage("");try{await action();setMessage(ok);await refresh();}catch(e){setError(e instanceof Error?e.message:"Operation failed");}finally{setBusy(false);}}
 function selectWorld(w:World){setWorldId(w.id);setSceneId(w.scenes[0]?.id??null);setLayerId(w.scenes[0]?.layers[0]?.id??null);}
 function selectScene(s:Scene){setSceneId(s.id);setLayerId(s.layers[0]?.id??null);}
 async function createWorld(){const key=`world-${Date.now()}`;await run(async()=>{const created=await mutate<World>("pinoria/worlds","POST",{key,displayName:"Untitled World",descriptionText:"",worldType:"CORE",thumbnailAssetKey:null,metadata:{}});setWorldId(created.id);},"World draft created");}
 async function saveWorld(status:Status){if(!world)return;await run(async()=>{await mutate(`pinoria/worlds/${world.id}`,"PATCH",{expectedVersion:world.version,displayName:world.displayName,descriptionText:world.descriptionText,worldType:world.worldType,thumbnailAssetKey:world.thumbnailAssetKey,metadata:world.metadata,status});},status==="ARCHIVED"?"World archived":"World saved");}
 function patchWorld(p:Partial<World>){if(!world)return;setCatalog(v=>v.map(x=>x.id===world.id?{...x,...p}:x));}
 async function deleteWorld(){if(!world||!confirm(`Founder delete ${world.displayName}?`))return;const force=confirm("Also force-delete any referenced WorldInstances? Cancel keeps referenced state protected.");await run(async()=>{await mutate(`pinoria/worlds/${world.id}`,"DELETE",{force});setWorldId(null);},"World deleted");}
 async function createScene(file:File){if(!world)return;await run(async()=>{const media=await upload(file);if(media.mediaType!=="PNG")throw new Error("Scene base must be PNG in V1");const created=await mutate<Scene>(`pinoria/worlds/${world.id}/scenes`,"POST",{expectedWorldVersion:world.version,key:`scene-${Date.now()}`,displayName:"Untitled Scene",descriptionText:"",canvasWidth:1920,canvasHeight:1080,baseAssetKey:media.objectKey,metadata:{},character:{positionX:0,positionY:15,scale:1,zIndex:30}});setSceneId(created.id);setLayerId(created.layers[0]?.id??null);},"Scene created with mandatory Character layer");}
 function patchScene(p:Partial<Scene>){if(!world||!scene)return;setCatalog(v=>v.map(w=>w.id!==world.id?w:{...w,scenes:w.scenes.map(s=>s.id===scene.id?{...s,...p}:s)}));}
 async function saveScene(){if(!scene)return;await run(async()=>{await mutate(`pinoria/worlds/scenes/${scene.id}`,"PATCH",{expectedVersion:scene.version,displayName:scene.displayName,descriptionText:scene.descriptionText,sortOrder:scene.sortOrder,status:scene.status,canvasWidth:scene.canvasWidth,canvasHeight:scene.canvasHeight,baseAssetKey:scene.baseAssetKey,metadata:scene.metadata});},"Scene saved");}
 async function replaceBase(file:File){if(!scene)return;await run(async()=>{const media=await upload(file);if(media.mediaType!=="PNG")throw new Error("Scene base must be PNG in V1");patchScene({baseAssetKey:media.objectKey});await mutate(`pinoria/worlds/scenes/${scene.id}`,"PATCH",{expectedVersion:scene.version,displayName:scene.displayName,descriptionText:scene.descriptionText,sortOrder:scene.sortOrder,status:scene.status,canvasWidth:scene.canvasWidth,canvasHeight:scene.canvasHeight,baseAssetKey:media.objectKey,metadata:scene.metadata});},"Base replaced");}
 async function deleteScene(){if(!scene||!confirm(`Founder delete scene ${scene.displayName}?`))return;await run(async()=>{await mutate(`pinoria/worlds/scenes/${scene.id}`,"DELETE",{});setSceneId(null);},"Scene deleted");}
 async function addLayer(file:File){if(!scene)return;await run(async()=>{const media=await upload(file);const created=await mutate<Layer>(`pinoria/worlds/scenes/${scene.id}/layers`,"POST",{expectedSceneVersion:scene.version,key:`layer-${Date.now()}`,displayName:file.name.replace(/\.[^.]+$/,""),mediaType:media.mediaType,assetKey:media.objectKey,posterAssetKey:null,positionX:0,positionY:0,scale:1,zIndex:Math.max(20,...scene.layers.map(x=>x.zIndex))+10,enabled:true,metadata:{}});setLayerId(created.id);},"Layer uploaded and added");}
 function patchLayer(p:Partial<Layer>){if(!world||!scene||!layer)return;setCatalog(v=>v.map(w=>w.id!==world.id?w:{...w,scenes:w.scenes.map(s=>s.id!==scene.id?s:{...s,layers:s.layers.map(l=>l.id===layer.id?{...l,...p}:l)})}));}
 async function saveLayer(){if(!layer)return;await run(async()=>{await mutate(`pinoria/worlds/layers/${layer.id}`,"PATCH",{expectedVersion:layer.version,...(layer.kind==="MEDIA"?{displayName:layer.displayName,mediaType:layer.mediaType,assetKey:layer.assetKey,posterAssetKey:layer.posterAssetKey,enabled:layer.enabled,metadata:layer.metadata}:{}),positionX:layer.positionX,positionY:layer.positionY,scale:layer.scale,zIndex:layer.zIndex});},layer.kind==="CHARACTER"?"Character placement saved":"Layer saved");}
 async function replaceLayer(file:File){if(!layer||layer.kind!=="MEDIA")return;await run(async()=>{const media=await upload(file);await mutate(`pinoria/worlds/layers/${layer.id}`,"PATCH",{expectedVersion:layer.version,displayName:layer.displayName,mediaType:media.mediaType,assetKey:media.objectKey,posterAssetKey:null,enabled:layer.enabled,metadata:layer.metadata,positionX:layer.positionX,positionY:layer.positionY,scale:layer.scale,zIndex:layer.zIndex});},"Layer asset replaced");}
 async function deleteLayer(){if(!layer||layer.kind!=="MEDIA"||!confirm(`Founder delete layer ${layer.displayName}?`))return;await run(async()=>{await mutate(`pinoria/worlds/layers/${layer.id}`,"DELETE",{});setLayerId(null);},"Layer deleted");}
 async function grant(w:World){if(!learner)return;await run(async()=>{const created=await mutate<Instance>(`pinoria/worlds/learners/${learner.id}/instances`,"POST",{worldId:w.id,displayLabel:`${w.displayName} · Manual grant`});setInstanceId(created.id);},"WorldInstance granted INACTIVE");}
 async function instanceCommand(command:"set-live"|"revoke"|"reactivate"){if(!instance)return;await run(async()=>{await mutate(`pinoria/worlds/instances/${instance.id}/${command}`,"POST",{});},command==="set-live"?"LIVE switched atomically":"WorldInstance updated");}
 async function deleteInstance(){if(!instance||!confirm(`Founder hard-delete ${instance.displayLabel}?`))return;await run(async()=>{await mutate(`pinoria/worlds/instances/${instance.id}`,"DELETE",{});setInstanceId(null);},"WorldInstance deleted");}
 async function sceneAccess(sceneId:string,accessible:boolean){if(!instance)return;await run(async()=>{await mutate(`pinoria/worlds/instances/${instance.id}/scenes/${sceneId}`,"PUT",{accessible});},accessible?"Scene enabled":"Scene disabled");}
 async function unlock(layerId:string,unlocked:boolean){if(!instance)return;await run(async()=>{await mutate(`pinoria/worlds/instances/${instance.id}/layers/${layerId}`,"PUT",{unlocked});},unlocked?"Layer unlocked":"Layer relocked");}
 return <main className={styles.page}>
  <header className={styles.hero}><div><p className={styles.eyebrow}>PINORIA · WORLD FOUNDATION V1</p><h1>World Studio</h1><p>Core-backed manual authoring and learner WorldInstance control. Character is a required dynamic Scene layer.</p></div><div className={styles.heroActions}><span className={styles.prototypeBadge}>CORE BACKED</span><div className={styles.modeSwitch}><button className={mode==="WORLD"?styles.modeActive:""} onClick={()=>setMode("WORLD")}>World Builder</button><button className={mode==="INSTANCE"?styles.modeActive:""} onClick={()=>setMode("INSTANCE")}>Student Instances</button></div></div></header>
  <section className={styles.metrics}><Metric label="Worlds" value={catalog.length} note="canonical definitions"/><Metric label="Scenes" value={totals.scenes} note="N scenes supported"/><Metric label="Layers" value={totals.layers} note="media + required character"/><Metric label="Progression" value="Manual" note="policy intentionally absent"/></section>
  {error?<div className={styles.foundationNote}><b>Error</b><span>{error}</span></div>:null}{message?<div className={styles.foundationNote}><b>Saved</b><span>{message}</span></div>:null}
  {mode==="WORLD"?<section className={styles.builderGrid}>
   <aside className={styles.library}><div className={styles.panelTitle}><div><span>Definitions</span><strong>World library</strong></div><button disabled={busy} onClick={()=>void createWorld()}>+</button></div><div className={styles.worldList}>{catalog.map(w=><button key={w.id} className={world?.id===w.id?styles.worldActive:""} onClick={()=>selectWorld(w)}><i data-type={w.worldType}>{w.worldType==="CORE"?"◈":"✦"}</i><span><strong>{w.displayName}</strong><small>{w.key} · {w.worldType}</small></span><em data-status={w.status}>{w.status}</em></button>)}</div></aside>
   <section className={styles.canvasPanel}>{world&&scene?<><div className={styles.canvasHead}><div><span>{world.worldType} REGION</span><h2>{world.displayName}</h2><p>{world.descriptionText||"Manual V1 definition"}</p></div><div className={styles.sceneTabs}>{world.scenes.map(s=><button key={s.id} className={scene.id===s.id?styles.sceneTabActive:""} onClick={()=>selectScene(s)}>{s.displayName}</button>)}</div></div><WorldStage scene={scene}/><div className={styles.canvasMeta}><span>Canvas <b>{scene.canvasWidth} × {scene.canvasHeight}</b></span><span>Base <code>{scene.baseAssetKey}</code></span></div></>:<div className={styles.empty}>Create a World and Scene to begin.</div>}</section>
   <aside className={styles.inspector}>{world?<><div className={styles.panelTitle}><div><span>World</span><strong>{world.displayName}</strong></div></div><div className={styles.layerEditor}><label>Name<input value={world.displayName} onChange={e=>patchWorld({displayName:e.target.value})}/></label><label>Description<input value={world.descriptionText} onChange={e=>patchWorld({descriptionText:e.target.value})}/></label><div className={styles.twoFields}><label>Type<select value={world.worldType} onChange={e=>patchWorld({worldType:e.target.value as WorldType})}><option>CORE</option><option>SUMMER</option><option>SPECIAL</option><option>OTHER</option></select></label><label>Status<select value={world.status} onChange={e=>patchWorld({status:e.target.value as Status})}><option>DRAFT</option><option>ACTIVE</option><option>ARCHIVED</option></select></label></div><button disabled={busy} onClick={()=>void saveWorld(world.status)}>Save World</button><button className={styles.deleteButton} onClick={()=>void deleteWorld()}>Founder delete World</button><label>New Scene base PNG<input type="file" accept="image/png" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void createScene(f);e.currentTarget.value="";}}/></label></div></>:null}
    {scene?<><hr/><div className={styles.panelTitle}><div><span>Scene</span><strong>{scene.displayName}</strong></div></div><div className={styles.layerEditor}><label>Name<input value={scene.displayName} onChange={e=>patchScene({displayName:e.target.value})}/></label><div className={styles.threeFields}><label>W<input type="number" value={scene.canvasWidth} onChange={e=>patchScene({canvasWidth:n(e.target.value)})}/></label><label>H<input type="number" value={scene.canvasHeight} onChange={e=>patchScene({canvasHeight:n(e.target.value)})}/></label><label>Order<input type="number" value={scene.sortOrder} onChange={e=>patchScene({sortOrder:n(e.target.value)})}/></label></div><button disabled={busy} onClick={()=>void saveScene()}>Save Scene</button><label>Replace base PNG<input type="file" accept="image/png" onChange={e=>{const f=e.target.files?.[0];if(f)void replaceBase(f);e.currentTarget.value="";}}/></label><label>Add media layer<input type="file" accept="image/png,video/webm" onChange={e=>{const f=e.target.files?.[0];if(f)void addLayer(f);e.currentTarget.value="";}}/></label><button className={styles.deleteButton} onClick={()=>void deleteScene()}>Founder delete Scene</button></div><div className={styles.layerStack}>{scene.layers.map((l,i)=><button key={l.id} className={layer?.id===l.id?styles.layerActive:""} onClick={()=>setLayerId(l.id)}><span className={styles.layerIndex}>{String(i+1).padStart(2,"0")}</span><span className={styles.layerName}><strong>{l.displayName}</strong><small>{l.kind==="CHARACTER"?"DYNAMIC":l.mediaType} · z{l.zIndex}</small></span>{l.kind==="CHARACTER"?<em>FIXED</em>:null}</button>)}</div></>:null}
    {layer?<div className={styles.layerEditor}><div className={styles.editorHead}><div><span>Layer inspector</span><strong>{layer.displayName}</strong></div></div>{layer.kind==="CHARACTER"?<div className={styles.characterInvariant}><b>Required Character Layer</b><span>Current learner Character + Ward render projection. Always on; not unlockable or deletable.</span></div>:<><label>Name<input value={layer.displayName} onChange={e=>patchLayer({displayName:e.target.value})}/></label><label>Asset <input value={layer.assetKey??""} disabled/></label><label>Replace PNG/WebM<input type="file" accept="image/png,video/webm" onChange={e=>{const f=e.target.files?.[0];if(f)void replaceLayer(f);e.currentTarget.value="";}}/></label></>}<div className={styles.threeFields}><label>X<input type="number" value={layer.positionX} onChange={e=>patchLayer({positionX:n(e.target.value)})}/></label><label>Y<input type="number" value={layer.positionY} onChange={e=>patchLayer({positionY:n(e.target.value)})}/></label><label>Scale<input type="number" step=".05" value={layer.scale} onChange={e=>patchLayer({scale:n(e.target.value)})}/></label></div><label>Z-index<input type="number" value={layer.zIndex} onChange={e=>patchLayer({zIndex:n(e.target.value)})}/></label>{layer.kind==="MEDIA"?<label className={styles.switchLine}><span><b>Enabled</b></span><input type="checkbox" checked={layer.enabled} onChange={e=>patchLayer({enabled:e.target.checked})}/></label>:null}<button disabled={busy} onClick={()=>void saveLayer()}>Save layer</button>{layer.kind==="MEDIA"?<button className={styles.deleteButton} onClick={()=>void deleteLayer()}>Founder delete layer</button>:null}</div>:null}
   </aside>
  </section>:<section className={styles.instanceWorkspace}>
   <aside className={styles.studentRail}><div className={styles.panelTitle}><div><span>Learners</span><strong>Student context</strong></div></div>{learners.map(l=><button key={l.id} className={learner?.id===l.id?styles.studentActive:""} onClick={()=>{setStudentId(l.id);setInstanceId(null)}}><span className={styles.avatar}>{l.displayName.split(" ").at(-1)?.slice(0,2).toUpperCase()}</span><span><strong>{l.displayName}</strong><small>{l.instanceCount} WorldInstances</small></span></button>)}</aside>
   <div className={styles.instancesPanel}>{learner?<><div className={styles.instanceHero}><div><span className={styles.avatarLarge}>{learner.displayName.split(" ").at(-1)?.slice(0,2).toUpperCase()}</span><div><span>Student WorldInstances</span><h2>{learner.displayName}</h2><p>Multiple allowed · database enforces 0..1 LIVE</p></div></div><div className={styles.grantMenu}><span>Grant</span>{catalog.filter(w=>w.status!=="ARCHIVED").map(w=><button key={w.id} disabled={busy} onClick={()=>void grant(w)}>+ {w.displayName}</button>)}</div></div><div className={styles.instanceCards}>{instances.map(i=><button key={i.id} className={instance?.id===i.id?styles.instanceCardActive:""} onClick={()=>{setInstanceId(i.id);setInstanceSceneId(i.world.scenes[0]?.id??null);void api<Instance>(`pinoria/worlds/instances/${i.id}`).then(detail=>setInstances(rows=>rows.map(row=>row.id===detail.id?detail:row))).catch(e=>setError(e instanceof Error?e.message:"Instance load failed"));}}><div><i data-world={i.world.worldType}>{i.world.worldType==="CORE"?"◈":"✦"}</i><span><strong>{i.displayLabel}</strong><small>{i.world.key} · {i.grantedAt.slice(0,10)}</small></span></div><em data-status={i.status}>{i.status}</em></button>)}</div></>:null}
    {instance?<div className={styles.instanceDetail}><div className={styles.instanceDetailHead}><div><span>WorldInstance</span><h3>{instance.displayLabel}</h3><code>{instance.id}</code></div><div className={styles.instanceActions}>{instance.status==="INACTIVE"?<button className={styles.primary} onClick={()=>void instanceCommand("set-live")}>Set LIVE</button>:null}{instance.status!=="REVOKED"?<button onClick={()=>void instanceCommand("revoke")}>Revoke</button>:<button onClick={()=>void instanceCommand("reactivate")}>Reactivate</button>}<button className={styles.deleteButton} onClick={()=>void deleteInstance()}>Delete</button></div></div><div className={styles.instanceBody}><div className={styles.instanceConfig}><div className={styles.sceneAccessTabs}>{instance.world.scenes.map(s=><button key={s.id} className={instanceScene?.id===s.id?styles.sceneTabActive:""} onClick={()=>setInstanceSceneId(s.id)}>{s.displayName}</button>)}</div>{instanceScene?<><label className={styles.accessToggle}><span><b>Scene access</b><small>Manual primitive; Keygate automation later.</small></span><input type="checkbox" disabled={instance.status==="REVOKED"} checked={Boolean(instance.sceneAccess[instanceScene.id])} onChange={e=>void sceneAccess(instanceScene.id,e.target.checked)}/></label><div className={styles.unlockList}><div className={styles.unlockBase}><span><i>BASE</i><strong>{instanceScene.baseAssetKey}</strong></span><em>Always rendered</em></div>{instanceScene.layers.map(l=>l.kind==="CHARACTER"?<div key={l.id} className={styles.characterInstanceRow}><span><b>◆</b><strong>Character</strong><small>Dynamic learner · {l.anchor} · z{l.zIndex}</small></span><em>ALWAYS ON</em></div>:<label key={l.id}><input type="checkbox" disabled={instance.status==="REVOKED"||!instance.sceneAccess[instanceScene.id]} checked={instance.unlockedLayerIds.includes(l.id)} onChange={e=>void unlock(l.id,e.target.checked)}/><span><strong>{l.displayName}</strong><small>{l.mediaType} · {l.key}</small></span><em>{instance.unlockedLayerIds.includes(l.id)?"UNLOCKED":"LOCKED"}</em></label>)}</div></>:null}</div><div className={styles.runtimePreview}><div className={styles.runtimeHead}><div><span>Runtime projection</span><strong>{instance.status==="LIVE"?"LIVE WORLD":"Preview instance"}</strong></div><em data-status={instance.status}>{instance.status}</em></div>{instanceScene&&instance.sceneAccess[instanceScene.id]?<WorldStage scene={instanceScene} unlocked={new Set(instance.unlockedLayerIds)} character={instance.character??null} compact/>:<div className={styles.lockedPreview}><strong>Scene locked</strong></div>}</div></div></div>:null}
   </div>
  </section>}
 </main>;
}
function Metric({label,value,note}:{label:string;value:string|number;note:string}){return <article className={styles.metric}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function WorldStage({scene,unlocked,character,compact=false}:{scene:Scene;unlocked?:Set<string>;character?:Character;compact?:boolean}){const base=pinoriaAssetUrl(scene.baseAssetKey);return <div className={compact?`${styles.stage} ${styles.stageCompact}`:styles.stage} style={{backgroundImage:base?`url(${base})`:undefined,backgroundSize:"cover",backgroundPosition:"center",aspectRatio:`${scene.canvasWidth} / ${scene.canvasHeight}`}}><div className={styles.stageGlow}/>{[...scene.layers].sort((a,b)=>a.zIndex-b.zIndex).map(l=>{if(l.kind==="MEDIA"&&(!l.enabled||(unlocked&&!unlocked.has(l.id))))return null;const anchorY=l.kind==="CHARACTER"&&l.anchor==="BOTTOM_CENTER"?"-100%":"-50%";const style={left:`${50+l.positionX}%`,top:`${50+l.positionY}%`,zIndex:l.zIndex,transform:`translate(-50%,${anchorY}) scale(${l.scale})`};if(l.kind==="CHARACTER")return <div key={l.id} className={styles.characterLayer} style={style}>{character?<LayeredCharacter className={styles.worldCharacter} config={character.config} wardRender={character.wardRender}/>:<LayeredCharacter className={styles.worldCharacter} config={{hair:"pinoria/char-base.png",face:"pinoria/char-base.png",outfit:"pinoria/char-base.png"}}/>}</div>;const src=pinoriaAssetUrl(l.assetKey);return <div key={l.id} className={styles.mediaLayer} style={style}>{l.mediaType==="WEBM"?<video src={src??undefined} autoPlay loop muted playsInline/>:<img src={src??undefined} alt=""/>}</div>})}<div className={styles.stageCaption}><span>{scene.displayName}</span></div></div>}
