import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("BO Learning/Syllabus renders the approved F0 authoring surface",async()=>{const [navigation,page,desk,api]=await Promise.all([readFile("app/bo/navigation.ts","utf8"),readFile("app/bo/syllabus/page.tsx","utf8"),readFile("app/bo/syllabus/LearningSyllabusDesk.tsx","utf8"),readFile("lib/bo-api.ts","utf8")]);assert.match(navigation,/label: "Learning"/);assert.match(navigation,/href: "\/bo\/syllabus", label: "Programs & Syllabus"/);assert.match(page,/LearningSyllabusDesk/);assert.match(desk,/Owner type/);assert.match(desk,/HOUSE_PATH|House Path/);assert.match(desk,/TOPPI_PROGRAM|Toppi Program/);assert.match(desk,/Create Syllabus/);assert.match(desk,/Save DRAFT/);assert.match(desk,/Review & Publish/);assert.match(desk,/Version history/);assert.match(desk,/Archive with reason/);assert.match(desk,/does not rewrite Sessions, Open Studio Listings, Journey, Content access, or Toppi progression/);for(const method of ["learningSyllabusOwners","learningSyllabi","learningSyllabus","createLearningSyllabus","saveLearningSyllabusDraft","publishLearningSyllabusDraft","createNextLearningSyllabusDraft","archiveLearningSyllabus"])assert.match(api,new RegExp(method));});

test("Syllabus BO stays generic and does not invent client authority or domain-specific payload",async()=>{const source=await readFile("app/bo/syllabus/LearningSyllabusDesk.tsx","utf8");assert.doesNotMatch(source,/NOTION|localStorage|sessionStorage|permissionKeys|canPublish|isFounder/);assert.doesNotMatch(source,/slides|worksheet|fingering|sheet music|lesson timeline|materials/i);assert.match(source,/boApi\.publishLearningSyllabusDraft/);assert.match(source,/payload\(form,draft\)/);assert.match(source,/thumbnailMediaId:preserve\?\.thumbnailMediaId\?\?null/);assert.match(source,/coverMediaId:preserve\?\.coverMediaId\?\?null/);assert.match(source,/provenance:preserve\?\.provenance\?\?null/);assert.match(source,/confirm\(/);});

test("owner-scoped profile editing does not hard-depend on global Media Library enumeration",async()=>{const source=await readFile("app/bo/syllabus/SyllabusProfileEditor.tsx","utf8");const load=source.slice(source.indexOf("async function load("),source.indexOf("async function practiceChoices("));assert.doesNotMatch(load,/syllabusWorksheetMedia\(/);assert.match(source,/async function toggleLibrary\(\)/);assert.match(source,/try\{setLibrary\(await boApi\.syllabusWorksheetMedia\(\)\);\}catch/);assert.doesNotMatch(source,/missingMedia\.length>0\|\|!canSave/);});
