import test from "node:test";
import assert from "node:assert/strict";
import { handleBoOperationalReadRequest, isPracticeReadPath, type BoReadEnv } from "./bo-read-handler";
import type { BoAccessCoreBinding, BoAccessRequest } from "./bo-core";
const token="local-password-session";
const req=(path:string,authenticated=true,method="GET")=>new Request(`https://bo.pinohouse.art/api/bo/${path}?email=forged&userId=forged`,{method,headers:authenticated?{cookie:`pino_staff_password_session=${token}`}:{}});
const env=(binding:BoAccessCoreBinding):BoReadEnv=>({PINO_BO_CORE:binding});
test("BO reads forward exact bounded requests with local password session",async()=>{const forwarded:Array<{request:BoAccessRequest;token:string}>=[];const binding:BoAccessCoreBinding={async executeWithStaffPassword(request,value){forwarded.push({request,token:value});return{status:200,body:{data:[]},requestId:"read"};}};const paths=["delivery/bootstrap-state","running-classes","practice/resources","workforce/staff-registration-settings"];for(const path of paths)assert.equal((await handleBoOperationalReadRequest(req(path),env(binding),path)).status,200);assert.deepEqual(forwarded.map(x=>x.request),paths.map(path=>({method:"GET",path})));assert.ok(forwarded.every(x=>x.token===token));});
test("missing local password session fails before Core",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;throw new Error("unexpected");}};assert.equal((await handleBoOperationalReadRequest(req("sessions",false),env(binding),"sessions")).status,401);assert.equal(called,false);});
test("unknown paths and non-GET methods fail closed",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;throw new Error("unexpected");}};assert.equal((await handleBoOperationalReadRequest(req("bookings"),env(binding),"bookings")).status,404);assert.equal((await handleBoOperationalReadRequest(req("sessions",true,"POST"),env(binding),"sessions")).status,405);assert.equal(called,false);});
test("query projection strips forged identity fields",async()=>{const forwarded:BoAccessRequest[]=[];const binding:BoAccessCoreBinding={async executeWithStaffPassword(request){forwarded.push(request);return{status:200,body:{data:[]},requestId:"learners"};}};const request=new Request("https://bo.pinohouse.art/api/bo/learners?query=Mai&limit=20&offset=200&userId=forged",{headers:{cookie:`pino_staff_password_session=${token}`}});await handleBoOperationalReadRequest(request,env(binding),"learners");assert.deepEqual(forwarded,[{method:"GET",path:"learners",body:{query:"Mai",limit:20,offset:200}}]);});
test("Core denial and request id pass through",async()=>{const binding:BoAccessCoreBinding={async executeWithStaffPassword(){return{status:403,body:{error:{code:"ACCESS_PERMISSION_DENIED"}},requestId:"denied"};}};const response=await handleBoOperationalReadRequest(req("running-classes"),env(binding),"running-classes");assert.equal(response.status,403);assert.equal(response.headers.get("x-request-id"),"denied");});
test("Practice read allowlist remains bounded",()=>{assert.equal(isPracticeReadPath("practice/repertoire-access/context"),true);assert.equal(isPracticeReadPath("practice/repertoire-access"),true);assert.equal(isPracticeReadPath("practice/repertoire-access/grants"),false);});

test("Session shared Syllabus binding read stays exact and bounded",async()=>{const id="0198d050-56c1-7ac5-b9ab-b0e45d912345",path=`delivery/sessions/${id}/syllabus-binding`,forwarded:BoAccessRequest[]=[];const binding:BoAccessCoreBinding={async executeWithStaffPassword(request){forwarded.push(request);return{status:200,body:{data:{sessionId:id,bindingState:"UNBOUND"}},requestId:"binding-read"};}};const response=await handleBoOperationalReadRequest(req(path),env(binding),path);assert.equal(response.status,200);assert.deepEqual(forwarded,[{method:"GET",path}]);assert.equal((await handleBoOperationalReadRequest(req(`delivery/sessions/${id}/syllabus-binding/extra`),env(binding),`delivery/sessions/${id}/syllabus-binding/extra`)).status,404);});
