import test from "node:test";
import assert from "node:assert/strict";
import { handleBoStaffOnboardingRequest, isPracticeWritePath, type BoWriteEnv } from "./bo-write-handler";
import type { BoAccessCoreBinding, BoAccessRequest } from "./bo-core";
const token="local-password-session",path="workforce/staff-onboarding";
const env=(binding:BoAccessCoreBinding):BoWriteEnv=>({PINO_BO_CORE:binding});
function request(route=path,authenticated=true,body:unknown={},idempotencyKey?:string,method="POST"){const headers:Record<string,string>={"content-type":"application/json"};if(authenticated)headers.cookie=`pino_staff_password_session=${token}`;if(idempotencyKey)headers["idempotency-key"]=idempotencyKey;return new Request(`https://bo.pinohouse.art/api/bo/${route}`,{method,headers,...(method==="GET"?{}:{body:JSON.stringify(body)})});}
test("BO writes forward exact request and password token",async()=>{const forwarded:Array<{request:BoAccessRequest;token:string}>=[];const binding:BoAccessCoreBinding={async executeWithStaffPassword(coreRequest,value){forwarded.push({request:coreRequest,token:value});return{status:201,body:{data:{ok:true}},requestId:"created"};}};const body={commandType:"ONBOARD_STAFF_WITH_ACCESS",staff:{displayLabel:"Staff A"},email:"staff@example.com",assignments:[]};const response=await handleBoStaffOnboardingRequest(request(path,true,body,"command-1"),env(binding),path);assert.equal(response.status,201);assert.deepEqual(forwarded,[{request:{method:"POST",path,body,idempotencyKey:"command-1"},token}]);});
test("missing local session fails before Core",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;throw new Error("unexpected");}};assert.equal((await handleBoStaffOnboardingRequest(request(path,false,{},"k"),env(binding),path)).status,401);assert.equal(called,false);});
test("replay protected paths require idempotency",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;throw new Error("unexpected");}};assert.equal((await handleBoStaffOnboardingRequest(request(path,true,{}),env(binding),path)).status,400);assert.equal(called,false);});
test("Staff PIN reset rejects manager-selected PIN",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;return{status:200,body:{data:{}},requestId:"x"};}};const reset="access/users/0198d050-56c1-7ac5-b9ab-b0e45d912345/staff-pin/reset";assert.equal((await handleBoStaffOnboardingRequest(request(reset,true,{pin:"123456"},"reset-1"),env(binding),reset)).status,400);assert.equal(called,false);});
test("Core denial and request ID pass through",async()=>{const binding:BoAccessCoreBinding={async executeWithStaffPassword(){return{status:403,body:{error:{code:"ACCESS_PERMISSION_DENIED"}},requestId:"denied"};}};const response=await handleBoStaffOnboardingRequest(request(path,true,{},"k"),env(binding),path);assert.equal(response.status,403);assert.equal(response.headers.get("x-request-id"),"denied");});
test("Practice allowlist stays bounded",()=>{const id="0198d050-56c1-7ac5-b9ab-b0e45d912345";assert.equal(isPracticeWritePath("practice/repertoire-access/grants"),true);assert.equal(isPracticeWritePath(`practice/repertoire-access/grants/${id}/revoke`),true);assert.equal(isPracticeWritePath("practice/media"),false);});
test("unknown paths and wrong methods fail closed",async()=>{let called=false;const binding:BoAccessCoreBinding={async executeWithStaffPassword(){called=true;throw new Error("unexpected");}};assert.equal((await handleBoStaffOnboardingRequest(request("access/users",true,{},"k"),env(binding),"access/users")).status,404);assert.equal((await handleBoStaffOnboardingRequest(request(path,true,{},undefined,"GET"),env(binding),path)).status,405);assert.equal(called,false);});
