"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { boApi, BoApiError } from "@/lib/bo-api";
import type { BoCenter, BoUnscheduledCheckInRequest } from "@/lib/bo-model";
import styles from "../bo.module.css";

type Load={state:"loading"}|{state:"error";message:string}|{state:"ready";rows:BoUnscheduledCheckInRequest[]};
export function CheckInExceptionsView(){
 const[centers,setCenters]=useState<BoCenter[]>([]),[centerId,setCenterId]=useState(""),[status,setStatus]=useState<""|BoUnscheduledCheckInRequest["status"]>("REQUESTED"),[load,setLoad]=useState<Load>({state:"loading"}),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<BoUnscheduledCheckInRequest|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const mutationAttempt=useRef<{signature:string;key:string}|null>(null);
 const selected=useMemo(()=>load.state==="ready"?load.rows.find(row=>row.id===selectedId)??null:null,[load,selectedId]);
 useEffect(()=>{void boApi.scopeCatalog().then(data=>{setCenters(data.centers);const center=data.centers.find(item=>item.status==="active")??data.centers[0];if(center)setCenterId(center.id)}).catch(error=>setLoad({state:"error",message:msg(error)}))},[]);
 useEffect(()=>{if(centerId)void refresh(centerId,status||undefined)},[centerId,status]);
 useEffect(()=>{if(!selectedId){setDetail(null);return}void boApi.workforceCheckInException(selectedId).then(setDetail).catch(error=>setNotice(msg(error)))},[selectedId]);
 async function refresh(center=centerId,nextStatus=status||undefined){setLoad({state:"loading"});setNotice("");try{const rows=await boApi.workforceCheckInExceptions(center,nextStatus);setLoad({state:"ready",rows});setSelectedId(current=>current&&rows.some(row=>row.id===current)?current:rows[0]?.id??null)}catch(error){setLoad({state:"error",message:msg(error)})}}
 function mutationKey(signature:string){if(!mutationAttempt.current||mutationAttempt.current.signature!==signature)mutationAttempt.current={signature,key:crypto.randomUUID()};return mutationAttempt.current.key}
 async function reconcileDetail(requestId:string,terminal:"APPROVED"|"DECLINED",successMessage:string,error:unknown){await refresh();try{const canonical=await boApi.workforceCheckInException(requestId);setDetail(canonical);if(canonical.status===terminal){mutationAttempt.current=null;setNotice(successMessage);return}setNotice(msg(error))}catch(readError){setNotice(msg(readError))}}
 async function approve(){if(!detail||detail.status!=="REQUESTED")return;const requestId=detail.id,version=detail.version,signature=`approve:${requestId}:${version}`;setBusy(true);setNotice("");try{await boApi.approveWorkforceCheckInException(requestId,version,mutationKey(signature));await reconcileDetail(requestId,"APPROVED","Đã duyệt. Core đã tạo assignment canonical cho nhân sự này.",new Error("Không thể xác nhận trạng thái duyệt."))}catch(error){await reconcileDetail(requestId,"APPROVED","Đã duyệt. Core đã tạo assignment canonical cho nhân sự này.",error)}finally{setBusy(false)}}
 async function decline(){if(!detail||detail.status!=="REQUESTED")return;const reason=prompt("Lý do từ chối (có thể để trống)")?.trim()||null,requestId=detail.id,version=detail.version,signature=`decline:${requestId}:${version}:${reason??""}`;setBusy(true);setNotice("");try{await boApi.declineWorkforceCheckInException(requestId,version,reason,mutationKey(signature));await reconcileDetail(requestId,"DECLINED","Yêu cầu đã được từ chối; không có assignment nào được tạo.",new Error("Không thể xác nhận trạng thái từ chối."))}catch(error){await reconcileDetail(requestId,"DECLINED","Yêu cầu đã được từ chối; không có assignment nào được tạo.",error)}finally{setBusy(false)}}
 return <div className={`${styles.page} ${styles.exceptionPage}`}>
  <header className={styles.heading}><span>Workforce · WFM-EXC</span><h1>Check-in Exceptions</h1><p>Review yêu cầu check-in ngoài lịch. Duyệt tạo một ca làm canonical; Timekeeping vẫn dùng flow check-in bình thường.</p></header>
  <div className={styles.exceptionFilters}><label className={styles.field}>Center<select value={centerId} onChange={e=>setCenterId(e.target.value)}>{centers.map(center=><option key={center.id} value={center.id}>{center.displayName}</option>)}</select></label><label className={styles.field}>Status<select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="">Tất cả</option>{["REQUESTED","APPROVED","DECLINED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select></label></div>
  {notice?<div className={styles.successCard}><strong>{notice}</strong></div>:null}
  <div className={styles.exceptionLayout}>
   <section className={styles.panel}>{load.state==="loading"?<div className={styles.state}>Đang tải queue canonical…</div>:load.state==="error"?<div className={`${styles.state} ${styles.errorState}`}>{load.message}</div>:load.rows.length===0?<div className={styles.empty}>Không có yêu cầu phù hợp.</div>:<div className={styles.exceptionList}>{load.rows.map(row=><button key={row.id} className={`${styles.exceptionRow} ${row.id===selectedId?styles.exceptionRowActive:""}`} onClick={()=>setSelectedId(row.id)}><div><strong>{row.staffDisplayLabel}</strong><span>{row.centerDisplayName} · {row.workDate}</span></div><p>{row.reason}</p><small>{new Date(row.requestedAt).toLocaleString("vi-VN")} · {row.status}</small></button>)}</div>}</section>
   <aside className={styles.exceptionSide}>{detail?<><div><span className={styles.statusPill}>{detail.status}</span><h2>{detail.staffDisplayLabel}</h2><p>{detail.centerDisplayName} · {detail.workDate}</p></div><dl className={styles.exceptionFacts}><div><dt>Lý do</dt><dd>{detail.reason}</dd></div><div><dt>Requested</dt><dd>{new Date(detail.requestedAt).toLocaleString("vi-VN")}</dd></div><div><dt>Version</dt><dd>{detail.version}</dd></div><div><dt>Request ID</dt><dd>{detail.id}</dd></div><div><dt>Assignment</dt><dd>{detail.generatedAssignmentId??"Chưa tạo"}</dd></div>{detail.declineReason?<div><dt>Lý do từ chối</dt><dd>{detail.declineReason}</dd></div>:null}</dl><div className={styles.exceptionNotice}>Approval sẽ tạo một StaffShiftAssignment canonical có provenance từ request này. Không có Manager override trực tiếp lên Timekeeping.</div><div className={styles.exceptionActions}><button className={styles.primaryButton} disabled={busy||detail.status!=="REQUESTED"} onClick={()=>void approve()}>Approve & tạo assignment</button><button className={styles.secondaryButton} disabled={busy||detail.status!=="REQUESTED"} onClick={()=>void decline()}>Decline</button></div></>:<div className={styles.empty}>Chọn một yêu cầu để review.</div>}</aside>
  </div>
 </div>
}
function msg(error:unknown){return error instanceof BoApiError?error.message:error instanceof Error?error.message:"Không thể tải dữ liệu từ Core."}
